feat: implement points in attend-event
HackRU/HackRU-Backend pull request #57
Opened 2024-09-14 23:34 UTC by DaStormer

Implemented points in the `attend-event` endpoint as per issue #56

2024-09-16 15:17 UTC, DaStormer commented on src/functions/attend-event/handler.ts
> +          await points.updateOne({ user_email: event.body.qr }, { $inc: { balance: event.body.points } });
good catch

2024-09-19 19:07 UTC, ethxng requested changes

2024-09-19 19:07 UTC, ethxng commented on src/functions/attend-event/handler.ts
> +      const userPoints = await points.findOne({ user_email: event.body.qr });
just need to change that to `email` (replace the rest too)

2024-09-20 00:31 UTC, ethxng approved these changes

2024-09-20 00:31 UTC, merged