Update buy ins
HackRU/HackRU-Backend pull request #72
Opened 2024-10-06 17:11 UTC by poojakedia

2024-10-13 16:12 UTC, kevinmonisit requested changes

2024-10-13 16:12 UTC, kevinmonisit commented on tests/update-buy-ins.test.ts
> +        { prize_id: 'prize2', buy_in: 10 },
wouldn't this be 10 + 5 = 15? if the user has 15 points, then they should be able to spend 15 points. perhaps just do one point over

2024-10-13 20:25 UTC, kevinmonisit commented
Hi pooja, there are few things you could do to improve this. Right now, I will do the changes for you so no worries.

Instead of nesting if statements, you could use something called Guard Clauses to improve the readability of your code.
See here: https://refactoring.guru/replace-nested-conditional-with-guard-clauses

Because the if statements were nested, it looks like you forgot to return an error when the lengths of buy ins and requested buy ins are not equal. When testing on Postman, I got a 502 Bad Gateway error instead of a more productive error message when the buy_in array had differing array lengths.

Those are the things I see at first glance, but thank you so much for you work! We are really happy for your contributions and I think the hundreds of hackers that will be using your work will appreciate it as well :) !!!

2024-10-14 02:06 UTC, ethxng approved these changes

2024-10-14 03:09 UTC, merged