Attend event
HackRU/HackRU-Backend pull request #8
Opened 2024-06-09 02:41 UTC by RyamL1221

Implemented attend_event endpoint

2024-06-09 23:20 UTC, ethxng requested changes
please fix what i've outlined in the comment. thank u ryan!

2024-06-09 23:20 UTC, ethxng commented on src/functions/attend_event/schema.ts
> +    required: ['qr', 'token', 'event']
auth_email is required --because we'll need it for a function called "ensure_role," which only allow users with certain roles (organizers and directors) to call this endpoint

2024-06-09 23:20 UTC, ethxng commented on src/functions/attend_event/handler.ts
> +    if(attend_event === null) {
add space between if and '('

2024-06-09 23:20 UTC, ethxng commented on src/functions/attend_event/handler.ts
> +    if(event.body.event > 0 && event.body.again === false) {
event.body.event is of type string; can't be compared to 0. we'll use event as key in our key:pair value in day_of object in Mongo

2024-06-09 23:20 UTC, ethxng commented on src/functions/attend_event/handler.ts
> +    if(event.body.event > 0 && event.body.again === false) {
you will need to check if the event exists already, and if it does, and its value is > 0 AND again = false, then you will return the message below

2024-06-09 23:20 UTC, ethxng commented on src/functions/attend_event/handler.ts
> +            statusCode: 402,
why 402?

2024-06-09 23:20 UTC, ethxng commented on src/functions/attend_event/handler.ts
> +        const result = await collection.findOne({ email });
you might need to write **{"email": email}** or else it won't know which attribute mongo needs to look for

2024-06-09 23:20 UTC, ethxng commented on src/functions/attend_event/handler.ts
> +        collection.updateOne({ ...result }, { $set: { dayOf: { event: event + 1 } } });
"event" not of type "int", but of type "string". if this "event" never exists in this day_of object: then set to 1, if it already exists, increment by 1

2024-06-09 23:20 UTC, ethxng commented on src/functions/attend_event/index.ts
> +        path: 'attend_event',
please add {cors: true} to allow cross-origin resource sharing

2024-06-09 23:51 UTC, RyamL1221 commented on src/functions/attend_event/handler.ts
> +            statusCode: 402,
LCS docs

2024-06-10 00:03 UTC, ethxng commented on src/functions/attend_event/handler.ts
> +            statusCode: 402,
actually lets change that. according to google 402 represents "Payment required," which is not exactly the message we want here. Lets change it to **409 Conflict**

2024-06-11 03:24 UTC, ethxng requested changes
i left a few more suggestions, feel free to ask me any questions! Also, please comment your code

2024-06-11 03:24 UTC, ethxng commented on src/functions/attend_event/handler.ts
> +        { $set: { 'day_of.event': result.day_of.event } }
does this target the specific event that match the "event" given the parameter?

2024-06-11 03:24 UTC, ethxng commented on src/functions/check_registration/handler.ts
> -const checkRegistration: ValidatedEventAPIGatewayProxyEvent<
lets keep it, we'll stick to camelCase for our project

2024-06-13 14:48 UTC, RyamL1221 commented on src/functions/attend_event/handler.ts
> +        { $set: { 'day_of.event': result.day_of.event } }
yes it does

2024-06-13 14:54 UTC, RyamL1221 commented on src/functions/attend_event/handler.ts
> +    const client = db.getClient();
created a function named connectToClient(mongoURI)

2024-06-30 19:59 UTC, merged